### PR TITLE
Add more aidanisms

### PR DESCRIPTION
**Pull request by joereynolds**

### CODE REVIEW

**Comment by tomdracz** [comment]
Hey @joereynolds 

Thanks for the PR, will happily merge. Keep 'em coming.

New gem version going live shortly

**Comment by AidanDavidWard** [comment]
I'm not sure how I feel about this @tomdracz & @joereynolds 😃

**Comment by tomdracz** [comment]
@AidanDavidWard Happy to receive PRs...
... or cease and desist 😄

**Comment by AidanDavidWard** [comment]
I brought this upon myself @tomdracz I heard they were mentioning creating their own version of this and so I thought I'd save them the trouble

**Pull request merged**
